// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

import 'flavors.dart';

class DefaultFirebaseOptionsEnv {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get android {
    switch (Flavor.flavorType) {
      case FlavorTypes.prod:
        return const FirebaseOptions(
          apiKey: 'xxx',
          appId: 'xxx',
          messagingSenderId: 'xxx',
          projectId: 'xxx',
          storageBucket: 'xxx.appspot.com',
        );

      case FlavorTypes.dev:
        return const FirebaseOptions(
          apiKey: 'xxx',
          appId: 'xxx',
          messagingSenderId: 'xxx',
          projectId: 'xxx',
          storageBucket: 'xxx.firebasestorage.app',
        );
      case FlavorTypes.sandbox:
        return const FirebaseOptions(
          apiKey: 'xxx',
          appId: '1:xxx:android:xxx',
          messagingSenderId: 'xxx',
          projectId: 'xxx-dev-xxx',
          storageBucket: 'xxx.firebasestorage.app',
        );

      case FlavorTypes.staging:
        return const FirebaseOptions(
          apiKey: 'xxx',
          appId: '1:xxx:android:xxx',
          messagingSenderId: 'xxx',
          projectId: 'xxx',
          storageBucket: 'xxx.firebasestorage.app',
        );
    }
  }

  static FirebaseOptions get ios {
    switch (Flavor.flavorType) {
      case FlavorTypes.prod:
        return const FirebaseOptions(
          apiKey: 'xxx-so64',
          appId: '1:xxx:ios:xxx',
          messagingSenderId: 'xxx',
          projectId: 'xxx',
          storageBucket: 'xxx.appspot.com',
          iosClientId: 'xxx-xxx.apps.googleusercontent.com',
          iosBundleId: 'xxx.app',
        );

      case FlavorTypes.dev:
        return const FirebaseOptions(
          apiKey: 'xxx',
          appId: '1:xxx:ios:xxx',
          messagingSenderId: 'xxx',
          projectId: 'xxx',
          storageBucket: 'xxx.firebasestorage.app',
          iosClientId: 'xxx-xxx.apps.googleusercontent.com',
          iosBundleId: 'xxx-app.dev',
        );

      case FlavorTypes.sandbox:
        return const FirebaseOptions(
          apiKey: 'xxx',
          appId: '1:xxx:ios:xxx',
          messagingSenderId: 'xxx',
          projectId: 'xxx',
          storageBucket: 'xxx.appspot.com',
          iosClientId: 'xxx-xxx.apps.googleusercontent.com',
          iosBundleId: 'xxx.app.dev',
        );

      case FlavorTypes.staging:
        return const FirebaseOptions(
          apiKey: 'xxx-xxx',
          appId: '1:xxx:ios:xxx',
          messagingSenderId: 'xxx',
          projectId: 'xxx',
          storageBucket: 'xxx.appspot.com',
          iosClientId: 'xxx-xxx.apps.googleusercontent.com',
          iosBundleId: 'xxx.app.dev',
        );
    }
  }
}
