import 'package:bibleplan/common.dart';
import 'package:bibleplan/providers/language_provider.dart';

const _ptWords = {
  "BIBLE": "BÍBLIA",
  "Bible": "Bíblia",
  "welcome": "Bem-vindo",
  "completed so far": "Concluído até aqui",
  "time to finish": "Tempo para conclusão",
  "full plan": "Ver Plano Completo",
  "today": "Hoje",
  "todays reading": "Leituras do Dia",
  "wait": "Aguarde",
  "read all bible in one year":
      "Em um ano você lerá toda a Bíblia e os livros da Série Conflito",
  "SPIRIT OF PROPHECY": "ESPÍRITO DE PROFECIA",
  "Spirit of prophecy": "Espírito de Profecia",
  "read spirit of prophecy": "Ler Espírito de Profecia",
  "read bible": "Ler a Bíblia",
  "chapters": "Capítulos",
  "chapter": "Capítulo",
  "chap": "Cap.",
  "done": "Concluído",
  "before": "Anterior",
  "next": "Próximo",
  "complete guide": "Guia Completo",
  "Reading Plan": "Plano de Leitura",
  "choose your language": "Escolha seu idioma",
  "choose font size": "Escolha o tamanho do texto",
  "small": "Pequeno",
  "medium": "Médio",
  "large": "Grande",
  "settings": "Configurações",
  "color": "Cor",
  "font size": "Tamanho da Letra",
  "about": "Sobre o App",
  "Bible Guide Study\nwith the Espirt of Prophecy":
      "Guia de Estudo da Bíblia\ncom o Espírito de Profecia",
  "light": "Claro",
  "dark": "Escuro",
  "language": "Idioma",
  "Dark Mode": "Modo Escuro",
  "automatic": "Automático",
  "Theme": "Tema",
  "PLAN": "Plano\n",
  "All": "Todos",
  "Not Read": "Não Lido",
  "Read": "Lido",
  "go to bible": "Ir para Texto Bíblico",
  "CONFIGURE ALARM": "Configurar Alarme",
  "Save Changes": "Salvar Alterações",
  "Delete": "Excluir",
  "All days": "Todos os Dias",
  "Repeat": "Repetir",
  "Reminders": "Lembretes",
  "Add reminder": "Adicionar Lembrete",
  "Week days": "Dias na Semana",
  "Weekends": "Fim de Semana",
  "Have you read your Bible today?": "Você já leu sua Bíblia hoje?",
  "Dont forget to take a time every day to read your Bible.":
      "Não esqueça de tirar um tempo diário para ler sua Bíblia",
  "Never": "Nunca",
  "End audio": "Encerrar Áudio",
  "Listen": "Ouvir",
  "DOWNLOADS": "Downloads",
  "DOWNLOADS BUTTON": "Downloads\n",
  "No audio available": "Nenhum Áudio Disponível",
  "NOTES AND HIGHLIGHTS": "Anotações e Marcações",
  "NOTES AND HIGHLIGHTS HOME": "Anotações \ne Marcações",
  "Open reference": "Abrir Local de Referência",
  "FILTER": "Filtro",
  "Clear": "Limpar",
  "Color": "Cor",
  "From": "De",
  "To": "Até",
  "Choose Date": "Escolher Data",
  "Save": "Salvar",
  "NOTE": "Anotação",
  "Highlights": "Marcações",
  "save note": "Salvar Anotação",
  "Edit": "Editar",
  "Notes": "Anotações",
  "SHARE": "COMPARTILHAR",
  "Choose a color": "Escolha uma cor",
  "Choose a font": "Escolha uma fonte",
  "Image": "Imagem",
  "Text": "Texto",
  "Are you sure that you want to reset your reading plan?":
      "Tem certeza que deseja limpar seu plano de leitura?",
  "Yes": "Sim",
  "No": "Não",
  "Warning": "Atenção",
  "Reset Plan": "Limpar plano de leitura",
  "Page": "Página",
  "Presentation": "Apresentação",
  "Presentation Text":
      "    A Palavra de Deus é um tesouro que contém tudo quanto é essencial para desenvolver e aperfeiçoar o ser humano. Não há alimento mais precioso para fortalecer a mente do que seu estudo. Por isso, Jesus disse: “Examinais as Escrituras, porque julgais ter nelas a vida eterna, e são elas mesmas que testificam de Mim” (João 5:39). Se a Palavra de Deus fosse estudada como deveria, as pessoas teriam um pensamento mais claro e um caráter mais nobre.\n\n    O propósito deste aplicativo é despertar a consciência e o desejo de entender mais profundamente as verdades da Palavra de Deus. Para tanto, você contará com o auxílio dos escritos de Ellen G. White, os quais ampliarão sua compreensão e fortalecerão sua fé nas verdades reveladas por Deus em Sua Palavra. Que esta ferramenta seja luz para seus caminhos (Salmo 119:105), até o glorioso dia em que veremos Jesus Cristo face a face.",
  "ShareApp": "Compartilhe o App Bible Plan",
  "ShareAppSubject": "Conheça o Aplicativo Bible Plan",
  "CheckOutThisApp":
      "📖 | VOCÊ CONHECE O BIBLE PLAN?\n\nO Bible Plan é um app de estudo da Bíblia em um ano (ano bíblico), acompanhado da leitura de cinco obras literárias da série conflito (Patriarcas e Profetas, Profetas e Reis, O Desejado de Todas as Nações, Atos dos Apóstolos, Grande Conflito e também com a obra Parábolas de Jesus 📚\n\nBaixe agora nas plataformas digitais.",
  "logoutButton": "Encerrar Sessão",
  "logoutTitle": "Encerrar Sessão",
  "logoutMessage": "Deseja realmente encerrar sua sessão?",
  "logoutConfirmPositive": "Sim",
  "logoutConfirmNegative": "Cancelar",
  // About Page
  "about_title":
      "BIBLE PLAN\nGuia de Estudo da Bíblia com auxílio do Espírito de Profecia",
  "about_subtitle":
      "Igreja Adventista do Sétimo Dia\nDivisão Sul-Americana\nDepartamento do Espírito de Profecia",
  "about_president": "Presidente: ",
  "about_secretary": "Secretário: ",
  "about_treasurer": "Tesoureiro: ",
  "about_cpegwTitle": "Centro de Pesquisas Ellen G. White",
  "about_generalDirectorate": "Direção Geral:",
  "about_executiveDirectorate": "Direção Executiva:",
  "about_technicalAssistant": "Assistente Técnico:",
  "about_reviewOfVerses": "Revisão de Passagens:",
  "about_development": "Desenvolvimento",
  // Login Page
  "loginTitle": "Bible Plan",
  "loginDescription": "App para estudo da Bíblia e do Espírito de Profecia",
  "loginApple": "Continuar com Apple",
  "loginGoogle": "Continuar com Google",
  "loginAnonymous": "Continuar sem Conta",
};

const _esWords = {
  "BIBLE": "BIBLIA",
  "Bible": "Biblia",
  "welcome": "Bienvenido",
  "completed so far": "Completado hasta aquí",
  "time to finish": "Tiempo de finalización",
  "full plan": "Ver Guía Completa",
  "today": "Hoy",
  "todays reading": "Lecturas del dia",
  "wait": "Espere",
  "read all bible in one year": "En un año leerás toda la Biblia y seis libros",
  "SPIRIT OF PROPHECY": "ESPÍRITU DE PROFECÍA",
  "Spirit of prophecy": "Espíritu de profecía",
  "read spirit of prophecy": "Leer Espíritu de Profecía",
  "read bible": "Leer la Biblia",
  "chapters": "CAPÍTULOS",
  "chapter": "Capítulo",
  "chap": "Cap.",
  "done": "Concluido",
  "before": "Anterior",
  "next": "Próximo",
  "complete guide": "Guía Completa",
  "choose your language": "Seleccione su idioma",
  "choose font size": "Elige el tamaño del texto",
  "small": "Pequeño",
  "medium": "Medio",
  "large": "Grande",
  "settings": "Ajustes",
  "color": "Color",
  "font size": "Tamaño de Fuente",
  "about": "Acerca",
  "Bible Guide Study\nwith the Espirt of Prophecy":
      "Guía de estudio bíblico\ncon el espíritu de profecía",
  "light": "Claro",
  "dark": "Oscuro",
  "language": "Idioma",
  "Dark Mode": "Modo Oscuro",
  "automatic": "Automático",
  "Theme": "Tema",
  "PLAN": "PLAN\n",
  "All": "Todos",
  "Not Read": "No Leído",
  "Read": "Leído",
  "go to bible": "Ir para el texto Bíblico",
  "CONFIGURE ALARM": "CONFIGURAR ALARMA",
  "Save Changes": "Guardar Cambios",
  "Delete": "Eliminar",
  "All days": "Todos los días",
  "Repeat": "Repetir",
  "Reminders": "Recordatorios",
  "Add reminder": "Agregar recordatorio",
  "Reading Plan": "Plan de Lectura",
  "Have you read your Bible today?": "Ya leyó su Biblia hoy?",
  "Dont forget to take a time every day to read your Bible.":
      "No olvide de tomarse un tiempo todo dia para leer su Biblia",
  "Never": "Nunca",
  "End audio": "Finalizar audio",
  "Listen": "Escuchar",
  "DOWNLOADS": "DESCARGAS",
  "DOWNLOADS BUTTON": "DESCARGAS\n",
  "No audio available": "Ningún audio disponible",
  "NOTES AND HIGHLIGHTS": "NOTAS Y DESTAQUES",
  "NOTES AND HIGHLIGHTS HOME": "NOTAS \nY DESTAQUES",
  "Open reference": "Abrir referencia",
  "FILTER": "FILTRO",
  "Clear": "Limpiar",
  "Color": "Color",
  "From": "De",
  "To": "Hacia",
  "Choose Date": "Escoger Fecha",
  "Save": "Guardar",
  "NOTE": "NOTA",
  "Highlights": "Destaques",
  "save note": "Guardar Nota",
  "Edit": "Editar",
  "Notes": "Notas",
  "SHARE": "COMPARTIR",
  "Choose a color": "Seleccione un color",
  "Choose a font": "Seleccione una fuente",
  "Image": "Imagen",
  "Text": "Texto",
  "Are you sure that you want to reset your reading plan?":
      "¿Estás seguro de que quieres borrar tu plan de lectura?",
  "Yes": "Si",
  "No": "No",
  "Warning": "Atencion",
  "Reset Plan": "Borrar plan de lectura",
  "Page": "Página",
  "Presentation": "Presentación",
  "Presentation Text":
      "    La Palabra de Dios es un tesoro que contiene todo lo esencial para el desarrollo y perfeccionamiento del ser humano. No hay alimento más preciado para fortalecer la mente que el estudio. Por eso, Jesús dijo: “Escudriñáis las Escrituras, porque pensáis que en ellas tenéis vida eterna, y ellas mismas dan testimonio de mí” (Juan 5:39). Si la Palabra de Dios se estudiara como se debe, las personas tendrían un pensamiento más claro y un carácter más noble.\n\n    El propósito de esta aplicación es despertar la conciencia y el deseo de comprender más profundamente las verdades de la Palabra de Dios. Para ello, contarás con la ayuda de los escritos de Elena G. de White, que ampliarán tu comprensión y fortalecerán tu fe en las verdades reveladas por Dios en Su Palabra. Que esta herramienta sea luz para tus caminos (Salmo 119:105), hasta el día glorioso en que veamos a Jesucristo cara a cara.",
  "ShareApp": "Comparte la aplicación del Plan Bíblico",
  "ShareAppSubject": "Descubre la aplicación del Plan Bíblico",
  "CheckOutThisApp":
      "📖 | ¿CONOCES EL PLAN BÍBLICO?\n\nEl Plan Bíblico es una aplicación de estudio bíblico de un año, que incluye la lectura de cinco obras literarias de la serie Controversia (Patriarcas y Profetas, Profetas y Reyes, El Deseado de Todas las Gentes, Hechos de los Apóstoles, El Gran Conflicto) y la obra Parábolas de Jesús. 📚\n\nDescárgalo ahora en plataformas digitales.",
  "logoutButton": "Cerrar sesión",
  "logoutTitle": "Cerrar sesión",
  "logoutMessage": "¿Desea realmente cerrar su sesión?",
  "logoutConfirmPositive": "Sí",
  "logoutConfirmNegative": "Cancelar",
  // About Page
  "about_title":
      "BIBLE PLAN\nGuía de estudio bíblico con la ayuda del Espíritu de profecía",
  "about_subtitle":
      "Iglesia Adventista del Séptimo Día\nDivisión Sudamericana\nDepartamento del Espíritu de Profecía",
  "about_president": "Presidente: ",
  "about_secretary": "Secretario: ",
  "about_treasurer": "Tesorero: ",
  "about_cpegwTitle": "Centro de Investigación Elena White",
  "about_generalDirectorate": "Dirección General:",
  "about_executiveDirectorate": "Dirección Ejecutiva:",
  "about_technicalAssistant": "Asistente Técnico:",
  "about_reviewOfVerses": "Revisión de Versos:",
  "about_development": "Desarrollo",
  // Login Page
  "loginTitle": "Bible Plan",
  "loginDescription":
      "Aplicación para el estudio de la Biblia y del Espíritu de Profecía",
  "loginApple": "Continuar con Apple",
  "loginGoogle": "Continuar con Google",
  "loginAnonymous": "Continuar sin cuenta",
};

const _enWords = {
  "BIBLE": "BIBLE",
  "Bible": "Bible",
  "welcome": "Welcome",
  "completed so far": "Completed so far",
  "time to finish": "Time to finish",
  "full plan": "Full Plan",
  "today": "Today",
  "todays reading": "Todays reading",
  "wait": "Wait",
  "read all bible in one year":
      "In one year you will read the entire Bible and the books of the Conflict of the Ages Series",
  "SPIRIT OF PROPHECY": "SPIRIT OF PROPHECY",
  "Spirit of prophecy": "Spirit of Prophecy",
  "read spirit of prophecy": "Read Spirit of Prophecy",
  "read bible": "Read the Bible",
  "chapters": "Chapters",
  "chapter": "Chapter",
  "chap": "Ch.",
  "done": "Completed",
  "before": "Previous",
  "next": "Next",
  "complete guide": "Complete Guide",
  "Reading Plan": "Reading Plan",
  "choose your language": "Choose your language",
  "choose font size": "Choose text size",
  "small": "Small",
  "medium": "Medium",
  "large": "Large",
  "settings": "Settings",
  "color": "Color",
  "font size": "Font Size",
  "about": "About the App",
  "Bible Guide Study\nwith the Spirit of Prophecy":
      "Bible Study Guide Bible\nwith the Spirit of Prophecy",
  "light": "Light",
  "dark": "Dark",
  "language": "Language",
  "Dark Mode": "Dark Mode",
  "automatic": "Automatic",
  "Theme": "Theme",
  "PLAN": "Plan\n",
  "All": "All",
  "Not Read": "Not Read",
  "Read": "Read",
  "go to bible": "Go to Bible Text",
  "CONFIGURE ALARM": "Set Alarm",
  "Save Changes": "Save Changes",
  "Delete": "Delete",
  "All days": "All Days",
  "Repeat": "Repeat",
  "Reminders": "Reminders",
  "Add reminder": "Add Reminder",
  "Week days": "Days of the Week",
  "Weekends": "Weekends",
  "Have you read your Bible today?": "Have you read your Bible today?",
  "Don't forget to take a time every day to read your Bible.":
      "Don't forget to take a time every day to read your Bible",
  "Never": "Never",
  "End audio": "End Audio",
  "Listen": "Listen",
  "DOWNLOADS": "Downloads",
  "DOWNLOADS BUTTON": "Downloads\n",
  "No audio available": "No Audio Available",
  "NOTES AND HIGHLIGHTS": "Notes and Highlights",
  "NOTES AND HIGHLIGHTS HOME": "Notes \nand Highlights",
  "Open reference": "Open Reference Location",
  "FILTER": "Filter",
  "Clear": "Clear",
  "Color": "Color",
  "From": "From",
  "To": "To",
  "Choose Date": "Choose Date",
  "Save": "Save",
  "NOTE": "Note",
  "Highlights": "Highlights",
  "save note": "Save Note",
  "Edit": "Edit",
  "Notes": "Notes",
  "SHARE": "SHARE",
  "Choose a color": "Choose a color",
  "Choose a font": "Choose a font",
  "Image": "Image",
  "Text": "Text",
  "Are you sure that you want to reset your reading plan?":
      "Are you sure that you want to clear your reading plan?",
  "Yes": "Yes",
  "No": "No",
  "Warning": "Warning",
  "Reset Plan": "Clear reading plan",
  "Page": "Page",
  "Presentation": "Presentation",
  "Presentation Text":
      "    The Word of God is a treasure that contains everything that is essential for developing and perfecting human beings. There is no more precious food to strengthen the mind than its study. That is why Jesus said: “You search the Scriptures, for in them you think you have eternal life; and they are they which testify of Me” (John 5:39). If the Word of God were studied as it should be, people would have clearer thinking and a nobler character.\n\n    The purpose of this application is to awaken awareness and the desire to understand more deeply the truths of the Word of God. To do so, you will have the help of the writings of Ellen G. White, which will broaden your understanding and strengthen your faith in the truths revealed by God in His Word. May this tool be a light for your path (Psalm 119:105), until the glorious day when we will see Jesus Christ face to face.",
  "ShareApp": "Share the Bible Plan App",
  "ShareAppSubject": "Discover the Bible Plan App",
  "CheckOutThisApp":
      "📖 | DO YOU KNOW THE BIBLE PLAN?\n\nThe Bible Plan is a one-year Bible study app (Bible year), accompanied by the reading of five literary works from the Controversy series (Patriarchs and Prophets, Prophets and Kings, The Desire of Ages, Acts of the Apostles, The Great Controversy) and also the work Parables of Jesus 📚\n\nDownload now on digital platforms.",
  "logoutButton": "Log out",
  "logoutTitle": "Log out",
  "logoutMessage": "Do you really want to log out?",
  "logoutConfirmPositive": "Yes",
  "logoutConfirmNegative": "Cancel",
  // About Page
  "about_title":
      "BIBLE PLAN\nBible Study Guide with the help of the Spirit of Prophecy",
  "about_subtitle":
      "Seventh-day Adventist Church\nSouth American Division\nDepartment of the Spirit of Prophecy",
  "about_president": "President: ",
  "about_secretary": "Secretary: ",
  "about_treasurer": "Treasurer: ",
  "about_cpegwTitle": "Ellen G. White Research Center",
  "about_generalDirectorate": "General Management:",
  "about_executiveDirectorate": "Executive Management:",
  "about_technicalAssistant": "Technical Assistant:",
  "about_reviewOfVerses": "Verse Review:",
  "about_development": "Development",
  // Login Page
  "loginTitle": "Bible Plan",
  "loginDescription": "App for studying the Bible and the Spirit of Prophecy",
  "loginApple": "Continue with Apple",
  "loginGoogle": "Continue with Google",
  "loginAnonymous": "Continue without an account",
};

const _frWords = {
  "BIBLE": "BIBLE",
  "Bible": "Bible",
  "welcome": "Bienvenue",
  "completed so far": "Terminé jusqu'à présent",
  "time to finish": "Temps pour terminer",
  "full plan": "Plan complet",
  "today": "Aujourd'hui",
  "todays reading": "Lecture d'aujourd'hui",
  "wait": "Attendez",
  "read all bible in one year":
      "En un an, vous lirez toute la Bible et les livres de la série Le Grand Conflit des Âges",
  "SPIRIT OF PROPHECY": "ESPRIT DE PROPHÉTIE",
  "Spirit of prophecy": "Esprit de Prophétie",
  "read spirit of prophecy": "Lire l'Esprit de Prophétie",
  "read bible": "Lire la Bible",
  "chapters": "Chapitres",
  "chapter": "Chapitre",
  "chap": "Chap.",
  "done": "Terminé",
  "before": "Précédent",
  "next": "Suivant",
  "complete guide": "Guide complet",
  "Reading Plan": "Plan de lecture",
  "choose your language": "Choisissez votre langue",
  "choose font size": "Choisir la taille du texte",
  "small": "Petit",
  "medium": "Moyen",
  "large": "Grand",
  "settings": "Paramètres",
  "color": "Couleur",
  "font size": "Taille de police",
  "about": "À propos de l'application",
  "Bible Guide Study\nwith the Spirit of Prophecy":
      "Guide d'étude biblique\navec l'Esprit de Prophétie",
  "light": "Clair",
  "dark": "Sombre",
  "language": "Langue",
  "Dark Mode": "Mode sombre",
  "automatic": "Automatique",
  "Theme": "Thème",
  "PLAN": "Plan\n",
  "All": "Tout",
  "Not Read": "Non lu",
  "Read": "Lu",
  "go to bible": "Aller au texte biblique",
  "CONFIGURE ALARM": "Configurer l'alarme",
  "Save Changes": "Enregistrer les modifications",
  "Delete": "Supprimer",
  "All days": "Tous les jours",
  "Repeat": "Répéter",
  "Reminders": "Rappels",
  "Add reminder": "Ajouter un rappel",
  "Week days": "Jours de la semaine",
  "Weekends": "Fins de semaine",
  "Have you read your Bible today?": "Avez-vous lu votre Bible aujourd'hui ?",
  "Don't forget to take a time every day to read your Bible.":
      "N'oubliez pas de prendre du temps chaque jour pour lire votre Bible",
  "Never": "Jamais",
  "End audio": "Arrêter l'audio",
  "Listen": "Écouter",
  "DOWNLOADS": "Téléchargements",
  "DOWNLOADS BUTTON": "Téléch.\n",
  "No audio available": "Aucun audio disponible",
  "NOTES AND HIGHLIGHTS": "Notes et surlignages",
  "NOTES AND HIGHLIGHTS HOME": "Notes et \nsurlignages",
  "Open reference": "Ouvrir la référence",
  "FILTER": "Filtrer",
  "Clear": "Effacer",
  "Color": "Couleur",
  "From": "De",
  "To": "À",
  "Choose Date": "Choisir la date",
  "Save": "Enregistrer",
  "NOTE": "Note",
  "Highlights": "Surlignages",
  "save note": "Enregistrer la note",
  "Edit": "Modifier",
  "Notes": "Notes",
  "SHARE": "PARTAGER",
  "Choose a color": "Choisir une couleur",
  "Choose a font": "Choisir une police",
  "Image": "Image",
  "Text": "Texte",
  "Are you sure that you want to reset your reading plan?":
      "Êtes-vous sûr de vouloir réinitialiser votre plan de lecture ?",
  "Yes": "Oui",
  "No": "Non",
  "Warning": "Avertissement",
  "Reset Plan": "Réinitialiser le plan de lecture",
  "Page": "Page",
  "Presentation": "Présentation",
  "Presentation Text":
      " La Parole de Dieu est un trésor qui contient tout ce qui est essentiel pour développer et perfectionner l'être humain. Il n'existe pas de nourriture plus précieuse pour fortifier l'esprit que son étude. C'est pourquoi Jésus a dit : « Vous sondez les Écritures, parce que vous pensez avoir en elles la vie éternelle : ce sont elles qui rendent témoignage de moi » (Jean 5:39). Si la Parole de Dieu était étudiée comme elle devrait l'être, les gens auraient une pensée plus claire et un caractère plus noble.\n\n Le but de cette application est d'éveiller la conscience et le désir de comprendre plus profondément les vérités de la Parole de Dieu. Pour cela, vous aurez l'aide des écrits d'Ellen G. White, qui élargiront votre compréhension et renforceront votre foi dans les vérités révélées par Dieu dans Sa Parole. Que cet outil soit une lumière sur votre sentier (Psaume 119:105), jusqu'au jour glorieux où nous verrons Jésus-Christ face à face.",
  "ShareApp": "Partagez l'application du plan biblique",
  "ShareAppSubject": "Découvrez l'application Bible Plan.",
  "CheckOutThisApp":
      "📖 | CONNAISSEZ-VOUS LE PLAN D'ÉTUDE BIBLIQUE ?\n\nLe Plan d'étude biblique est une application d'étude biblique d'un an (année biblique), accompagnée de la lecture de cinq ouvrages de la série Controverse (Patriarches et Prophètes, Prophètes et Rois, Le Désir des siècles, Actes des Apôtres, La Grande Controverse) ainsi que de l'ouvrage Les Paraboles de Jésus. 📚\n\nTéléchargez-le dès maintenant sur les plateformes numériques.",
  "logoutButton": "Se déconnecter",
  "logoutTitle": "Se déconnecter",
  "logoutMessage": "Souhaitez-vous vraiment vous déconnecter ?",
  "logoutConfirmPositive": "Oui",
  "logoutConfirmNegative": "Annuler",
  // About Page
  "about_title":
      "BIBLE PLAN\nGuide d'étude biblique avec l'aide de l'Esprit de Prophétie",
  "about_subtitle":
      "Église Adventiste du Septième Jour\nDivision Sud-Américaine\nDépartement de l'Esprit de Prophétie",
  "about_president": "Président : ",
  "about_secretary": "Secrétaire : ",
  "about_treasurer": "Trésorier : ",
  "about_cpegwTitle": "Centre de Recherche Ellen G. White",
  "about_generalDirectorate": "Direction Générale :",
  "about_executiveDirectorate": "Direction Exécutive :",
  "about_technicalAssistant": "Assistant Technique :",
  "about_reviewOfVerses": "Révision des Versets :",
  "about_development": "Développement",
  // Login Page
  "loginTitle": "Bible Plan",
  "loginDescription":
      "Application pour l’étude de la Bible et de l’Esprit de prophétie",
  "loginApple": "Continuer avec Apple",
  "loginGoogle": "Continuer avec Google",
  "loginAnonymous": "Continuer sans compte",
};

const _zhCNWords = {
  "BIBLE": "圣经",
  "Bible": "圣经",
  "welcome": "欢迎",
  "completed so far": "已完成",
  "time to finish": "完成时间",
  "full plan": "完整计划",
  "today": "今天",
  "todays reading": "今日阅读",
  "wait": "请稍候",
  "read all bible in one year": "一年内，您将阅读完整本圣经和善恶之争系列丛书",
  "SPIRIT OF PROPHECY": "预言之灵",
  "Spirit of prophecy": "预言之灵",
  "read spirit of prophecy": "阅读预言之灵",
  "read bible": "阅读圣经",
  "chapters": "章节",
  "chapter": "章",
  "chap": "章",
  "done": "完成",
  "before": "上一页",
  "next": "下一页",
  "complete guide": "完整指南",
  "Reading Plan": "阅读计划",
  "choose your language": "选择您的语言",
  "choose font size": "选择字体大小",
  "small": "小",
  "medium": "中",
  "large": "大",
  "settings": "设置",
  "color": "颜色",
  "font size": "字体大小",
  "about": "关于应用",
  "Bible Guide Study\nwith the Spirit of Prophecy": "圣经学习指南\n与预言之灵",
  "light": "浅色",
  "dark": "深色",
  "language": "语言",
  "Dark Mode": "深色模式",
  "automatic": "自动",
  "Theme": "主题",
  "PLAN": "计划\n",
  "All": "全部",
  "Not Read": "未读",
  "Read": "已读",
  "go to bible": "前往圣经文本",
  "CONFIGURE ALARM": "配置提醒",
  "Save Changes": "保存更改",
  "Delete": "删除",
  "All days": "每天",
  "Repeat": "重复",
  "Reminders": "提醒",
  "Add reminder": "添加提醒",
  "Week days": "工作日",
  "Weekends": "周末",
  "Have you read your Bible today?": "您今天读圣经了吗？",
  "Don't forget to take a time every day to read your Bible.": "别忘了每天花时间阅读圣经",
  "Never": "从不",
  "End audio": "停止音频",
  "Listen": "收听",
  "DOWNLOADS": "下载",
  "DOWNLOADS BUTTON": "下载\n",
  "No audio available": "无音频可用",
  "NOTES AND HIGHLIGHTS": "笔记和标注",
  "NOTES AND HIGHLIGHTS HOME": "笔记和\n标注",
  "Open reference": "打开参考",
  "FILTER": "筛选",
  "Clear": "清除",
  "Color": "颜色",
  "From": "从",
  "To": "到",
  "Choose Date": "选择日期",
  "Save": "保存",
  "NOTE": "笔记",
  "Highlights": "标注",
  "save note": "保存笔记",
  "Edit": "编辑",
  "Notes": "笔记",
  "SHARE": "分享",
  "Choose a color": "选择颜色",
  "Choose a font": "选择字体",
  "Image": "图片",
  "Text": "文本",
  "Are you sure that you want to reset your reading plan?": "您确定要重置阅读计划吗？",
  "Yes": "是",
  "No": "否",
  "Warning": "警告",
  "Reset Plan": "重置计划",
  "Page": "页",
  "Presentation": "介绍",
  "Presentation Text":
      "上帝的话语是一个宝库，包含了培养和完善人类所必需的一切。没有比研究圣经更宝贵的食粮来强化心智。这就是为什么耶稣说：\"你们查考圣经，因你们以为内中有永生；给我作见证的就是这经\"（约翰福音5:39）。如果人们能够像应该的那样研究上帝的话语，他们将拥有更清晰的思想和更高尚的品格。\n\n 本应用的目的是唤醒人们的意识和深入理解上帝话语真理的愿望。为此，您将获得怀爱伦著作的帮助，这将扩展您的理解并加强您对上帝在祂话语中启示的真理的信心。愿这个工具成为照亮您道路的光（诗篇119:105），直到我们面对面见到耶稣基督的荣耀之日",
  "ShareApp": "分享圣经计划应用程序",
  "ShareAppSubject": "探索圣经计划应用程序",
  "CheckOutThisApp":
      "📖 | 您了解“圣经计划”吗？\n\n“圣经计划”是一款为期一年的圣经学习应用程序（圣经年），配套阅读“争论”系列中的五部文学作品（《先祖与先知》、《先知与君王》、《历代愿望》、《使徒行传》、《善恶之争》）以及《耶稣的比喻》📚\n\n立即在各大数字平台下载。",
  "logoutButton": "退出登录",
  "logoutTitle": "退出登录",
  "logoutMessage": "您确定要退出登录吗？",
  "logoutConfirmPositive": "是",
  "logoutConfirmNegative": "取消",
  // About Page
  "about_title": "圣经计划\n圣经学习指南与预言之灵辅助",
  "about_subtitle": "基督复临安息日会\n南美分会\n预言之灵部",
  "about_president": "会长：",
  "about_secretary": "秘书：",
  "about_treasurer": "财务主管：",
  "about_cpegwTitle": "怀爱伦研究中心",
  "about_generalDirectorate": "总指导：",
  "about_executiveDirectorate": "执行主任：",
  "about_technicalAssistant": "技术助理：",
  "about_reviewOfVerses": "经文校对：",
  "about_development": "开发",
  // Login Page
  "loginTitle": "Bible Plan",
  "loginDescription": "用于学习圣经和预言之灵的应用程序",
  "loginApple": "使用 Apple 继续",
  "loginGoogle": "使用 Google 继续",
  "loginAnonymous": "无需账户继续",
};

String localize(String key) => _localize(key);

String _localize(String key) {
  var l = Language.instance.current;
  Map<String, String> map;
  switch (l) {
    case "es":
      map = _esWords;
    case "en":
      map = _enWords;
    case "pt":
      map = _ptWords;
    case "fr":
      map = _frWords;
    case "zh-CN":
      map = _zhCNWords;
    default:
      map = _enWords;
  }

  if (!map.containsKey(key)) {
    debugPrint("LOCALIZATION MISSING: '$key' not available for '$l'");
  }

  return map[key] ?? key;
}

extension ThemeModeLocalized on ThemeMode {
  String get localize {
    switch (this) {
      case ThemeMode.light:
        return _localize("light");
      case ThemeMode.dark:
        return _localize("dark");
      default:
        return _localize("automatic");
    }
  }
}
